name: Cloud Android Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Accept Android SDK Licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Make Gradle Executable
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew :app:assembleDebug -x test -x lint --stacktrace

    - name: Upload Compiled APK
      uses: actions/upload-artifact@v4
      with:
        name: Duck-Detector-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
